version: '3.6'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - tx-signer

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_LOGGERS: kafka.controller=ERROR,kafka.foo.bar=ERROR
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
    networks:
      - tx-signer

  jaeger:
    image: jaegertracing/all-in-one:1.8
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    networks:
      - tx-signer

  vault: # This is now completely broken
    image: library/vault:0.10.3
    tty: true
    # networks:
    #   - backend
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/:/vault/config/:ro
    ports:
      - 8200:8200
    environment: 
      - VAULT_ADDR=http://127.0.0.1:8200
    entrypoint: vault server -config=/vault/config/vault.json -log-level=trace

networks:
  tx-signer:
    driver: bridge
